version: "3.5"
services:
  flask:
    build:
      context: flask
    ports:
      - 8001:5000
    volumes:
      - ./flask:/usr/src/app
    environment:
      WP_API_URL: http://wp/wp-json
      WP_BACKEND_DOMAIN: http://localhost:8000

  wp:
    build:
      context: wp
    ports:
      - 8080:80
    working_dir: /var/www/html/wp-content/themes/headless-wp
    volumes:
      - ./wp/wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp/wp-content/themes:/var/www/html/wp-content/themes
      - ./wp/wp-content/uploads:/var/www/html/wp-content/uploads
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      RUN_SCRIPTS: 1
      PAGER: more
      COMPOSER_ALLOW_SUPERUSER: 1
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  db_data: {}
